# Generated by Django 5.0.7 on 2024-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='unit_quality_state',
            field=models.CharField(default='Buen estado', editable=False, max_length=50),
        ),
    ]
