# Generated by Django 5.0.7 on 2024-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0002_alter_productunit_unit_quality_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
