# Generated by Django 5.0.7 on 2024-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0003_alter_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='unit_quality_state',
            field=models.CharField(default='Good condition', editable=False, max_length=50),
        ),
    ]
