# Generated by Django 5.0.7 on 2024-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0005_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_assigned_suggestions',
            field=models.CharField(default='Blank', max_length=5000),
        ),
    ]
