# Generated by Django 5.1.2 on 2024-10-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('inventech', '0006_product_product_assigned_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assigned_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
            preserve_default=False,
        ),
    ]
