# Generated by Django 5.0.7 on 2024-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0007_product_assigned_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sales',
            field=models.IntegerField(default=0),
        ),
    ]
