# Generated by Django 5.0.7 on 2024-11-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventech', '0009_product_product_expiration_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='unit_location',
        ),
    ]
