# Generated by Django 5.0.7 on 2024-10-16 16:49

import django.db.models.deletion
import shipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idShippingCompany', models.CharField(default=shipment.models.generate_uuid, editable=False, max_length=50)),
                ('shipComp_name', models.CharField(max_length=45)),
                ('shipComp_phone', models.CharField(max_length=45)),
                ('shipComp_website', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idShipment', models.CharField(default=shipment.models.generate_uuid, editable=False, max_length=50)),
                ('shipmentDate', models.DateField()),
                ('shipment_address', models.CharField(max_length=45)),
                ('shipment_customer_name', models.CharField(max_length=45)),
                ('shipment_customer_lastname', models.CharField(max_length=45)),
                ('shipment_customer_phone', models.CharField(max_length=45)),
                ('shipment_customer_id', models.CharField(max_length=45)),
                ('shipment_units_quantity', models.IntegerField(default=0)),
                ('ShippingCompany_idShippingCompany', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.shippingcompany')),
            ],
        ),
    ]
